repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23 # Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Use the ref you want to point at
    hooks:
      - id: check-json
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: pretty-format-json
        args: [--autofix]
      - id: trailing-whitespace
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_checkov
      - id: terraform_docs
        args:
          - --hook-config=--add-to-existing-file=true # Boolean. true or false
          - --args=--config=.terraform-docs.yml
  - repo: local
    hooks:
      - id: tf-test.sh
        name: tf-test.sh
        entry: scripts/tf-test.sh
        language: script
        pass_filenames: false
      - id: cleanup.sh
        name: cleanup.sh
        entry: scripts/cleanup.sh
        language: script
        pass_filenames: false
