formatter: markdown

content: |-

  {{ .Header }}
  ## Examples

  ```hcl
  {{ include "example.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}
